# Generated by Django 2.1 on 2019-09-04 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nfl", "0002_auto_20190904_0735"),
    ]

    operations = [
        migrations.AlterField(
            model_name="week",
            name="file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="file",
                to="nfl.File",
            ),
        ),
    ]
