# Generated by Django 2.1 on 2019-09-04 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nfl", "0003_auto_20190904_0736"),
    ]

    operations = [
        migrations.RenameField(
            model_name="week",
            old_name="kind",
            new_name="gametype",
        ),
    ]
