# Generated by Django 2.1 on 2019-09-04 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nfl", "0004_auto_20190904_0952"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Week",
            new_name="Game",
        ),
    ]
