# Generated by Django 2.1 on 2019-09-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nfl", "0005_auto_20190904_1028"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="gametype",
            field=models.CharField(
                choices=[
                    ("HOF", "Hall of Fame"),
                    ("PRE", "Preseason"),
                    ("REG", "Regular Season"),
                    ("WC", "Wild Card"),
                    ("DIV", "Divisional Playoff"),
                    ("CON", "Conference Championship"),
                    ("SB", "Super Bowl"),
                ],
                max_length=4,
            ),
        ),
    ]
